title: "Gareth's Blog"
description: "Gareth's ideas in word form... mostly related to software development."

owner:
  name: "Gareth Aye"
  avatar: "bio-photo.jpg"
  bio: "Gareth is the founder of MathLeap, an online assessments platform for middle & high school math classes. Before starting MathLeap, Gareth led an engineering team at Mozilla Firefox. He lives in Portland, OR with his loving family."
  email: "gareth.aye@gmail.com"
  twitter: "garethforsomet"
  github: "gaye"

# Links to include in top navigation
# For external links add external: true
links:
  - title: Posts
    url: /posts/
  - title: MathLeap
    url: https://mathleap.org/
  - title: About
    url: /about/

timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: true
    coderay_line_numbers_start: 1
    coderay_tab_width: 2
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
